{
    "name": "Calendario Comercial",
    "summary": "Ecosistema comercial completo: calendario, seguimiento, planificación y ficha comercial",
    "version": "19.0.2.0.0",
    "category": "Sales",
    "author": "Skymedic",
    "website": "https://skymedic.es",
    "license": "AGPL-3",
    "depends": [
        "calendar",
        "contacts",
        "sale",
        "partner_activity_tags",
        "partner_volume_tags",
        "partner_trend_tags",
        "partner_crosssell_tags",
        "partner_frequency_tags",
    ],
    "data": [
        "security/commercial_calendar_security.xml",
        "security/ir.model.access.csv",
        "data/commercial_activity_type_data.xml",
        "data/calendar_event_type_data.xml",
        "data/commercial_followup_data.xml",
        "data/commercial_cron_data.xml",
        "views/calendar_event_views.xml",
        "views/commercial_followup_rule_views.xml",
        "views/res_partner_views.xml",
        "views/commercial_portfolio_views.xml",
        "wizard/commercial_quick_log_views.xml",
        "wizard/commercial_visit_planner_views.xml",
        "views/commercial_calendar_menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "commercial_calendar/static/src/**/*",
        ],
    },
    "installable": True,
    "application": False,
}
