{
    "name": "Shipping Management",
    "summary": "Hub centralizado de gestión de envíos en Inventario",
    "version": "19.0.3.0.0",
    "category": "Inventory/Delivery",
    "author": "Skymedic",
    "website": "https://skymedic.es",
    "license": "AGPL-3",
    "depends": [
        "stock_delivery",
        "delivery_carrier_account",
        "sale_stock",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/shipping_security.xml",
        "data/shipping_data.xml",
        "data/shipping_cron.xml",
        "data/shipping_sla_cron.xml",
        "wizard/shipping_batch_wizard.xml",
        "wizard/shipping_batch_send_wizard.xml",
        "wizard/shipping_rate_compare_wizard.xml",
        "views/shipping_shipment_views.xml",
        "views/shipping_label_views.xml",
        "views/stock_picking_views.xml",
        "views/sale_order_views.xml",
        "views/delivery_carrier_views.xml",
        "report/shipping_report_views.xml",
        "views/shipping_menu.xml",
    ],
    "post_init_hook": "_post_init_hook",
    "installable": True,
    "application": False,
}
